"""
PI Report Validation Pipeline — LangGraph Multi-Agent
======================================================
Uses a 4-node directed graph to validate PI reports before delivery:

  Researcher → Critic → Arbitrator → Formatter

The Critic is a second independent Claude instance that checks:
  1. Math accuracy  — re-derives every market sizing calculation
  2. Hallucination  — checks if cited sources plausibly exist
  3. Regulatory     — verifies FDA pathway details are correct
  4. Factual        — checks key epidemiological numbers

Flags are attached to the report and shown to the PI with severity levels.
"""

import json
import logging
from typing import TypedDict, Optional, List
from datetime import datetime

import httpx
from langgraph.graph import StateGraph, END

from app.core.config import settings

logger = logging.getLogger(__name__)

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
CRITIC_MODEL      = "claude-sonnet-4-6"   # fast + accurate for verification
TIMEOUT           = 120.0


# ── State ─────────────────────────────────────────────────────────────────────

class ValidationFlag(TypedDict):
    severity:    str   # "WARNING" | "NOTE"
    category:    str   # "MATH" | "HALLUCINATION" | "REGULATORY" | "FACTUAL"
    field:       str   # which field in the report was flagged
    issue:       str   # plain-English description of the issue
    suggestion:  str   # what the PI should verify


class PIReportState(TypedDict):
    # Input
    report:          dict           # full PIReport dict from Researcher
    product_type:    str

    expert_critic_rules: str = ""

    # Critic output
    flags:           List[ValidationFlag]
    critic_raw:      Optional[str]
    critic_error:    Optional[str]

    # Final output
    validated_report: Optional[dict]
    validation_passed: bool


# ── Helpers ───────────────────────────────────────────────────────────────────

async def _call_claude(system: str, user: str, max_tokens: int = 2000) -> str:
    async with httpx.AsyncClient(timeout=TIMEOUT) as client:
        r = await client.post(
            ANTHROPIC_API_URL,
            headers={
                "x-api-key":          settings.ANTHROPIC_API_KEY,
                "anthropic-version":  "2023-06-01",
                "content-type":       "application/json",
            },
            json={
                "model":      CRITIC_MODEL,
                "max_tokens": max_tokens,
                "system":     system,
                "messages":   [{"role": "user", "content": user}],
            }
        )
        r.raise_for_status()
        return r.json()["content"][0]["text"]


def _clean_json(raw: str) -> dict:
    clean = raw.strip()
    if clean.startswith("```"):
        parts = clean.split("```")
        clean = parts[1] if len(parts) > 1 else clean
        if clean.startswith("json"):
            clean = clean[4:]
    return json.loads(clean.strip())


# ── Node 1: Researcher ────────────────────────────────────────────────────────
# This node is a pass-through — the report is already generated by the
# alignment_service before the graph runs. We just validate the existing report.

async def researcher_node(state: PIReportState) -> PIReportState:
    """Pass-through — report already generated upstream."""
    logger.info("Validation graph: researcher node (pass-through)")
    return state


# ── Node 2: Critic ────────────────────────────────────────────────────────────

CRITIC_SYSTEM = """You are a rigorous scientific and regulatory critic reviewing AI-generated healthcare market intelligence reports.

Your job is to find errors — not to be helpful, but to be accurate. Check each of the following:

1. MATH: Re-derive every market sizing calculation from the stated inputs.
   - Extract: addressable_patients × price_per_course × penetration_rate
   - Re-calculate the TAM yourself
   - Flag if the stated TAM differs from your calculation by more than 5%
   - Flag if the formula text doesn't match the actual numbers

2. HALLUCINATION: For each source citation in disease_intelligence.data_points and regulatory_pathway.designations:
   - Assess whether the source plausibly exists (e.g. "CDC AR Threats Report 2019" — real. "IDSA 2023 CRE Specific Mortality Registry" — suspicious)
   - Flag any source that sounds invented, overly specific, or unlikely to exist
   - Do NOT flag well-known sources like CDC, FDA guidance documents, PubMed papers, CMS data

3. REGULATORY: Check FDA pathway details for antibiotics:
   - QIDP grants 5 additional years of exclusivity (not 3, not 7)
   - Priority Review means 6-month review clock (not 3, not 12)
   - Fast Track = rolling review + more FDA meetings (not accelerated approval)
   - LPAD requires labeling as "limited population"
   - NTAP provides up to 65-75% cost add-on above DRG threshold
   - Flag any of these that are stated incorrectly

4. FACTUAL: Check key epidemiological numbers:
   - CRE: ~13,100 U.S. infections, ~1,100 deaths annually (CDC 2019)
   - MRSA BSI: ~119,247 infections, ~19,832 deaths (CDC 2019)
   - C. difficile: ~223,900 cases, ~12,800 deaths (CDC 2019)
   - Sepsis: ~1.7M U.S. hospitalizations annually
   - Flag if stated numbers deviate from known values by more than 20%

Respond ONLY with valid compact JSON. Keep each "issue" and "suggestion" under 100 characters. Maximum 5 flags total.
{
  "flags": [
    {
      "severity": "WARNING",
      "category": "MATH",
      "field": "market_sizing.total_addressable_market_usd",
      "issue": "Stated TAM of $135M does not match formula: 9,000 × $15,000 × 25% = $33.75M, not $135M",
      "suggestion": "Verify the penetration rate assumption and recalculate TAM"
    }
  ],
  "overall_verdict": "PASS",
  "summary": "Report passed all checks with no significant issues"
}

If no issues found, return {"flags": [], "overall_verdict": "PASS", "summary": "All checks passed"}
Severity levels: WARNING = likely error, NOTE = minor concern or unverifiable claim
overall_verdict: PASS (no warnings), REVIEW (has notes only), FLAG (has warnings)"""


async def critic_node(state: PIReportState) -> PIReportState:
    """Second Claude instance reviews the report for errors."""
    logger.info("Validation graph: critic node running")

    # Build a focused summary of the report for the critic
    report = state["report"]
    ms     = report.get("market_sizing", {})
    di     = report.get("disease_intelligence", {})
    rp     = report.get("regulatory_pathway", {})

    # Extract key facts for the critic to check
    critic_input = {
        "product_type":    state["product_type"],
        "executive_summary": report.get("executive_summary", ""),
        "disease_data_points": di.get("data_points", []),
        "market_sizing": {
            "steps":   ms.get("steps", []),
            "formula": ms.get("formula", ""),
            "stated_TAM": ms.get("total_addressable_market_usd", 0),
            "stated_SAM": ms.get("serviceable_market_usd", 0),
        },
        "regulatory_designations": [
            {
                "name":        d.get("name", ""),
                "benefit":     d.get("benefit", ""),
                "source":      d.get("source", ""),
                "source_url":  d.get("source_url", ""),
            }
            for d in rp.get("designations", [])
        ],
        "friction_points": rp.get("key_friction_points", []),
        "funding_programs": rp.get("funding_programs", []),
    }

    try:
        expert_rules = state.get("expert_critic_rules", "")
        critic_sys = CRITIC_SYSTEM + ("\n\n" + expert_rules if expert_rules else "")
        raw = await _call_claude(
            system=critic_sys,
            user=f"Review this PI report extract:\n\n{json.dumps(critic_input, indent=2)}\n\nFind errors and return JSON. Be concise — max 80 chars per field.",
            max_tokens=3000,
        )
        # Try to parse; if truncated, attempt to salvage partial JSON
        try:
            data = _clean_json(raw)
        except Exception:
            # Attempt to extract flags array even from truncated JSON
            import re
            flags_match = re.search(r'"flags"\s*:\s*(\[.*?\])', raw, re.DOTALL)
            if flags_match:
                try:
                    data = {"flags": json.loads(flags_match.group(1)), "overall_verdict": "REVIEW"}
                except Exception:
                    data = {"flags": [], "overall_verdict": "PASS"}
            else:
                data = {"flags": [], "overall_verdict": "PASS"}

        flags = data.get("flags", [])
        logger.info(f"Critic found {len(flags)} flags, verdict: {data.get('overall_verdict')}")
        return {**state, "flags": flags, "critic_raw": raw, "critic_error": None}

    except Exception as e:
        logger.error(f"Critic node failed: {e}")
        return {**state, "flags": [], "critic_raw": None,
                "critic_error": f"Validation unavailable: {str(e)}"}


# ── Node 3: Arbitrator ────────────────────────────────────────────────────────

def arbitrator_node(state: PIReportState) -> PIReportState:
    """Decides routing based on critic findings."""
    flags    = state.get("flags", [])
    warnings = [f for f in flags if f.get("severity") == "WARNING"]
    notes    = [f for f in flags if f.get("severity") == "NOTE"]

    if warnings:
        verdict = "FLAG"
        passed  = False
        logger.warning(f"Arbitrator: {len(warnings)} warnings found — report flagged")
    elif notes:
        verdict = "REVIEW"
        passed  = True
        logger.info(f"Arbitrator: {len(notes)} notes found — report passes with notes")
    else:
        verdict = "PASS"
        passed  = True
        logger.info("Arbitrator: no issues — report passes validation")

    return {**state, "validation_passed": passed,
            "_verdict": verdict}   # internal routing key


def route_after_arbitrator(state: PIReportState) -> str:
    """Conditional edge: always go to formatter."""
    return "formatter"


# ── Node 4: Formatter ─────────────────────────────────────────────────────────

def source_formatter_node(state: PIReportState) -> PIReportState:
    """Extracts inline [SOURCE: url] markers and builds sources list."""
    try:
        from app.services.source_formatter import extract_and_format_sources
        report = extract_and_format_sources(state["report"].copy())
        logger.info(f"Source formatter: {len(report.get('sources', []))} sources extracted")
        return {**state, "report": report}
    except Exception as e:
        logger.warning(f"Source formatter failed: {e}")
        return state


def formatter_node(state: PIReportState) -> PIReportState:
    """Attaches validation results to the report."""
    report  = state["report"].copy()
    flags   = state.get("flags", [])
    passed  = state.get("validation_passed", True)
    error   = state.get("critic_error")
    verdict = state.get("_verdict", "PASS")

    warnings = [f for f in flags if f.get("severity") == "WARNING"]
    notes    = [f for f in flags if f.get("severity") == "NOTE"]

    report["validation"] = {
        "status":          verdict,
        "passed":          passed,
        "warnings":        warnings,
        "notes":           notes,
        "total_flags":     len(flags),
        "validator_model": CRITIC_MODEL,
        "validated_at":    datetime.utcnow().isoformat(),
        "error":           error,
        "summary": (
            error or
            (f"✓ All checks passed — no issues found" if not flags else
             f"⚠ {len(warnings)} warning(s) and {len(notes)} note(s) found — review flagged sections")
        )
    }

    logger.info(f"Formatter: validation complete — {verdict}")
    return {**state, "validated_report": report}


# ── Build Graph ───────────────────────────────────────────────────────────────

def build_validation_graph():
    """Build and compile the LangGraph validation pipeline."""
    graph = StateGraph(PIReportState)

    graph.add_node("researcher",       researcher_node)
    graph.add_node("critic",           critic_node)
    graph.add_node("arbitrator",       arbitrator_node)
    graph.add_node("source_formatter", source_formatter_node)
    graph.add_node("formatter",        formatter_node)

    graph.set_entry_point("researcher")
    graph.add_edge("researcher",       "critic")
    graph.add_edge("critic",           "arbitrator")
    graph.add_conditional_edges("arbitrator", route_after_arbitrator, {"source_formatter": "source_formatter", "formatter": "formatter"})
    graph.add_edge("source_formatter", "formatter")
    graph.add_edge("formatter",        END)

    return graph.compile()


# Compile once at module load
_validation_graph = None

def get_validation_graph():
    global _validation_graph
    if _validation_graph is None:
        _validation_graph = build_validation_graph()
    return _validation_graph


# ── Public entry point ────────────────────────────────────────────────────────

async def validate_pi_report(report: dict, product_type: str = "antibiotic") -> dict:
    """
    Run a PI report through the full validation graph.
    Returns the report with a 'validation' section attached.

    Args:
        report:       the PIReport dict from alignment_service
        product_type: product type string

    Returns:
        report dict with validation.status, validation.warnings, validation.notes
    """
    graph = get_validation_graph()

    initial_state: PIReportState = {
        "report":           report,
        "product_type":     product_type,
        "flags":            [],
        "critic_raw":       None,
        "critic_error":     None,
        "validated_report": None,
        "validation_passed": True,
        "expert_critic_rules": "",
    }

    # Inject domain-specific critic rules
    try:
        from app.services.expert_profiles import get_expert
        expert = get_expert(product_type)
        if expert:
            initial_state["expert_critic_rules"] = f"\n\nDOMAIN-SPECIFIC RULES ({expert.display_name}):\n{expert.critic_rules}"
    except Exception:
        pass

    try:
        final_state = await graph.ainvoke(initial_state)
        return final_state.get("validated_report", report)
    except Exception as e:
        logger.error(f"Validation graph failed: {e}")
        # Never block the report — attach error note and return
        report["validation"] = {
            "status":      "ERROR",
            "passed":      True,
            "warnings":    [],
            "notes":       [],
            "total_flags": 0,
            "error":       str(e),
            "summary":     "Validation service unavailable",
            "validated_at": datetime.utcnow().isoformat(),
        }
        return report
