"""
P1 strategic sections tests — S-01 through S-09.

Validates:
  S-01  Evidence Base: honest gap block when no primary research
  S-02  Value Driver Ranking: required third column (product_implication)
  S-03  Segment × Fit × Strategic Stance: ≥1 Explicit non-target enforced
  S-04  Feature Investment Posture: ≥1 Exclude enforced
  S-05  Pricing Model Trade-Off: ≥4 pricing models, structural_risk non-empty
  S-06  Adversarial Review: structural_risk required, fallback when API unavailable
  S-07  Positioning Statement: must contain "not" clause
  S-08  Strategic Risks: 3–5 items
  S-09  Guiding Question: non-empty string
"""

import asyncio
import pytest

# ── Helpers ───────────────────────────────────────────────────────────────────

def _run(coro):
    return asyncio.run(coro)


# ─────────────────────────────────────────────────────────────────────────────
# S-01 — Evidence Base & Methodology
# ─────────────────────────────────────────────────────────────────────────────

class TestEvidenceBase:
    """The evidence_base field is generated by the synthesis model.
    These tests verify its contract via schema inspection."""

    def test_evidence_base_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        fields = PIReport.model_fields
        assert "evidence_base" in fields

    def test_evidence_base_is_optional(self):
        from app.models.alignment import PIReport
        f = PIReport.model_fields["evidence_base"]
        # Optional fields have a default of None
        assert f.default is None

    def test_json_schema_contains_evidence_base(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "evidence_base" in EXPERT_JSON_SCHEMA
        assert "primary_research_present" in EXPERT_JSON_SCHEMA
        assert "evidence_gap_block" in EXPERT_JSON_SCHEMA

    def test_json_schema_evidence_base_has_limitations(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "limitations" in EXPERT_JSON_SCHEMA
        assert "decision_authority_profile" in EXPERT_JSON_SCHEMA


# ─────────────────────────────────────────────────────────────────────────────
# S-02 — Value Driver Ranking
# ─────────────────────────────────────────────────────────────────────────────

class TestValueDriverRanking:

    def test_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        assert "value_driver_ranking" in PIReport.model_fields

    def test_json_schema_has_product_implication_column(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "product_implication" in EXPERT_JSON_SCHEMA, \
            "S-02: schema must include product_implication (the key column from Gaidica)"

    def test_json_schema_has_relative_importance(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "relative_importance" in EXPERT_JSON_SCHEMA

    def test_schema_value_driver_ranking_is_list(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        # The schema shows it as an array starting with [
        idx = EXPERT_JSON_SCHEMA.find("value_driver_ranking")
        assert idx >= 0
        snippet = EXPERT_JSON_SCHEMA[idx:idx+40]
        assert "[" in snippet


# ─────────────────────────────────────────────────────────────────────────────
# S-03 — Segment × Fit × Strategic Stance
# ─────────────────────────────────────────────────────────────────────────────

class TestSegmentFitTable:

    def test_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        assert "segment_fit_table" in PIReport.model_fields

    def test_json_schema_mentions_explicit_non_target(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "Explicit non-target" in EXPERT_JSON_SCHEMA, \
            "S-03: schema must show 'Explicit non-target' as a valid stance value"

    def _parse_segment_table(self, rows):
        """Run the enforcement logic from _parse_expert_response."""
        from app.services.alignment_service import logger
        sft = [r for r in rows if isinstance(r, dict)]
        if sft and not any(
            "non-target" in (r.get("strategic_stance") or "").lower() for r in sft
        ):
            sft.append({
                "segment": "Segments outside primary buyer persona",
                "relative_fit": "Weak",
                "strategic_stance": "Explicit non-target",
                "rationale": "Enforced: every report must name at least one non-target segment.",
            })
        return sft

    def test_non_target_enforced_when_missing(self):
        rows = [
            {"segment": "Academic PIs", "relative_fit": "Strong", "strategic_stance": "Target", "rationale": "core buyer"},
            {"segment": "Hospitals", "relative_fit": "Moderate", "strategic_stance": "Selective", "rationale": "secondary"},
        ]
        result = self._parse_segment_table(rows)
        stances = [r["strategic_stance"] for r in result]
        assert any("non-target" in s.lower() for s in stances), \
            "Enforcement should add an Explicit non-target when missing"

    def test_non_target_not_duplicated_when_present(self):
        rows = [
            {"segment": "Academic PIs", "relative_fit": "Strong", "strategic_stance": "Target", "rationale": "core"},
            {"segment": "Enterprise IT", "relative_fit": "Weak", "strategic_stance": "Explicit non-target", "rationale": "not our buyer"},
        ]
        result = self._parse_segment_table(rows)
        non_target_count = sum(1 for r in result if "non-target" in r["strategic_stance"].lower())
        assert non_target_count == 1

    def test_empty_table_not_modified(self):
        result = self._parse_segment_table([])
        assert result == []


# ─────────────────────────────────────────────────────────────────────────────
# S-04 — Feature Investment Posture
# ─────────────────────────────────────────────────────────────────────────────

class TestFeatureInvestmentPosture:

    def test_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        assert "feature_investment_posture" in PIReport.model_fields

    def test_json_schema_has_exclude_posture(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "Exclude" in EXPERT_JSON_SCHEMA, \
            "S-04: schema must list 'Exclude' as a valid posture value"

    def test_json_schema_has_all_four_postures(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        for posture in ["Build and prioritize", "Build", "Selective", "Exclude"]:
            assert posture in EXPERT_JSON_SCHEMA, f"Missing posture: {posture}"

    def _parse_feature_posture(self, rows):
        fip = [r for r in rows if isinstance(r, dict)]
        if fip and not any(
            (r.get("posture") or "").lower() == "exclude" for r in fip
        ):
            fip.append({
                "feature_area": "Out-of-scope capabilities",
                "posture": "Exclude",
                "rationale": "Enforced: at least one Exclude required.",
            })
        return fip

    def test_exclude_enforced_when_missing(self):
        rows = [
            {"feature_area": "Data sync", "posture": "Build and prioritize", "rationale": "core"},
            {"feature_area": "Analytics", "posture": "Build", "rationale": "secondary"},
        ]
        result = self._parse_feature_posture(rows)
        postures = [r["posture"].lower() for r in result]
        assert "exclude" in postures

    def test_exclude_not_duplicated(self):
        rows = [
            {"feature_area": "Real-time streaming", "posture": "Exclude", "rationale": "penalises reliability"},
        ]
        result = self._parse_feature_posture(rows)
        assert sum(1 for r in result if r["posture"].lower() == "exclude") == 1


# ─────────────────────────────────────────────────────────────────────────────
# S-05 — Pricing Model Trade-Off Analysis
# ─────────────────────────────────────────────────────────────────────────────

class TestPricingModelAnalysis:

    def test_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        assert "pricing_model_analysis" in PIReport.model_fields

    def test_json_schema_has_model_comparison_table(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "model_comparison" in EXPERT_JSON_SCHEMA

    def test_json_schema_has_contextual_analysis_table(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "contextual_analysis" in EXPERT_JSON_SCHEMA

    def test_json_schema_has_structural_risk_in_pricing(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        # structural_risk must appear in the pricing section
        pricing_idx = EXPERT_JSON_SCHEMA.find("pricing_model_analysis")
        guiding_idx = EXPERT_JSON_SCHEMA.find("guiding_question")
        pricing_block = EXPERT_JSON_SCHEMA[pricing_idx:guiding_idx]
        assert "structural_risk" in pricing_block, \
            "S-05: pricing contextual_analysis must include structural_risk field"

    def test_json_schema_has_at_least_four_pricing_models_mentioned(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        required = ["metered", "subscription", "one-time", "hybrid"]
        schema_lower = EXPERT_JSON_SCHEMA.lower()
        for model in required:
            assert model in schema_lower, f"S-05: schema should mention '{model}' pricing model"

    def test_json_schema_has_user_appeal_and_sustainability(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "user_appeal" in EXPERT_JSON_SCHEMA
        assert "business_sustainability" in EXPERT_JSON_SCHEMA


# ─────────────────────────────────────────────────────────────────────────────
# S-06 — Adversarial Review
# ─────────────────────────────────────────────────────────────────────────────

from app.services.adversarial_review_service import (
    run_adversarial_review,
    validate_adversarial_review,
    _extract_recommendations,
    _fallback_review,
    _CRITIC_SYSTEM,
)


class TestAdversarialReviewService:

    def test_critic_system_mentions_structural_risk(self):
        assert "structural_risk" in _CRITIC_SYSTEM.lower()

    def test_critic_system_is_separate_from_synthesis(self):
        # The critic must explicitly frame itself as adversarial — "not to agree" or "critic"
        assert "not to agree" in _CRITIC_SYSTEM.lower() or "critic" in _CRITIC_SYSTEM.lower(), \
            "Critic system must contain 'not to agree' or 'critic' to signal adversarial stance"
        # It must NOT instruct the model to agree unconditionally
        lower = _CRITIC_SYSTEM.lower()
        assert "your job is to agree" not in lower and "you should agree" not in lower, \
            "Critic system must not instruct the model to simply agree with the report"

    def test_extract_recommendations_from_next_steps(self):
        report = {
            "recommended_next_steps": [
                "File provisional patent on core IP",
                "Apply to NSF SBIR Phase I",
                "Run 10 structured PI interviews",
            ]
        }
        recs = _extract_recommendations(report, "wearable data logger")
        assert len(recs) >= 3
        assert "File provisional patent" in recs[0]

    def test_extract_recommendations_caps_at_max(self):
        report = {
            "recommended_next_steps": [f"Step {i}" for i in range(20)]
        }
        recs = _extract_recommendations(report, "wearable")
        from app.services.adversarial_review_service import _MAX_RECOMMENDATIONS
        assert len(recs) <= _MAX_RECOMMENDATIONS

    def test_fallback_review_includes_all_recs(self):
        recs = ["Step A", "Step B", "Step C"]
        result = _fallback_review(recs)
        assert len(result) == 3
        for item in result:
            assert "structural_risk" in item
            assert item["structural_risk"].strip() != ""

    def test_fallback_review_structural_risk_non_empty(self):
        result = _fallback_review(["Do X"])
        assert result[0]["structural_risk"].strip() != ""

    def test_run_adversarial_review_no_api_key_returns_fallback(self):
        import os
        orig = os.environ.pop("ANTHROPIC_API_KEY", None)
        try:
            report = {"recommended_next_steps": ["Apply to NSF SBIR", "Run PI interviews"]}
            result = _run(run_adversarial_review(report, "wearable data logger"))
            assert isinstance(result, list)
            assert len(result) >= 1
            for item in result:
                assert item.get("structural_risk", "").strip() != ""
        finally:
            if orig:
                os.environ["ANTHROPIC_API_KEY"] = orig

    def test_run_adversarial_review_empty_report_returns_empty(self):
        result = _run(run_adversarial_review({}, "wearable"))
        assert result == []

    def test_validate_adversarial_review_enforces_structural_risk(self):
        items = [
            {"recommendation": "Do X", "supporting_case": "...", "structural_risk": "",
             "disconfirming_evidence": "None", "what_would_change_this": "..."},
        ]
        validated = validate_adversarial_review(items)
        assert len(validated) == 1
        assert validated[0]["structural_risk"].strip() != ""

    def test_validate_adversarial_review_drops_items_without_rec(self):
        items = [
            {"recommendation": "", "structural_risk": "some risk"},
            {"recommendation": "Valid step", "structural_risk": "concrete risk"},
        ]
        validated = validate_adversarial_review(items)
        assert len(validated) == 1
        assert validated[0]["recommendation"] == "Valid step"

    def test_adversarial_review_field_on_pireport(self):
        from app.models.alignment import PIReport
        assert "adversarial_review" in PIReport.model_fields


# ─────────────────────────────────────────────────────────────────────────────
# S-07 — Positioning Statement
# ─────────────────────────────────────────────────────────────────────────────

class TestPositioningStatement:

    def test_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        assert "positioning_statement" in PIReport.model_fields

    def test_json_schema_mentions_not_clause(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        ps_idx = EXPERT_JSON_SCHEMA.find("positioning_statement")
        snippet = EXPERT_JSON_SCHEMA[ps_idx:ps_idx+200]
        assert "NOT" in snippet or "not" in snippet, \
            "S-07: schema instruction must require a 'not' clause"

    def test_not_clause_enforcement_appends_when_missing(self):
        """Simulate the _parse_expert_response enforcement logic."""
        pos_stmt = "This product reliably captures long-duration neurophysiology data for academic labs."
        if " not " not in pos_stmt.lower() and "isn't" not in pos_stmt.lower():
            pos_stmt = pos_stmt.rstrip(".") + ". This product is not intended as [specify non-target use]."
        assert " not " in pos_stmt.lower()

    def test_not_clause_not_appended_when_already_present(self):
        pos_stmt = "This product is reliability-first data infrastructure — it is not a real-time streaming platform."
        original = pos_stmt
        if " not " not in pos_stmt.lower() and "isn't" not in pos_stmt.lower():
            pos_stmt += " [enforcement added]"
        assert pos_stmt == original   # unchanged — "not" already present


# ─────────────────────────────────────────────────────────────────────────────
# S-08 — Strategic Risks
# ─────────────────────────────────────────────────────────────────────────────

class TestStrategicRisks:

    def test_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        assert "strategic_risks" in PIReport.model_fields

    def test_json_schema_mentions_scope_creep_and_mispricing(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        schema_lower = EXPERT_JSON_SCHEMA.lower()
        assert "scope creep" in schema_lower or "scope" in schema_lower
        assert "mispric" in schema_lower

    def test_json_schema_specifies_3_to_5_items(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "3 to 5" in EXPERT_JSON_SCHEMA or "3–5" in EXPERT_JSON_SCHEMA or \
               "3-5" in EXPERT_JSON_SCHEMA


# ─────────────────────────────────────────────────────────────────────────────
# S-09 — Guiding Question
# ─────────────────────────────────────────────────────────────────────────────

class TestGuidingQuestion:

    def test_field_exists_on_pireport(self):
        from app.models.alignment import PIReport
        assert "guiding_question" in PIReport.model_fields

    def test_json_schema_mentions_decision_test(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        assert "guiding_question" in EXPERT_JSON_SCHEMA
        schema_lower = EXPERT_JSON_SCHEMA.lower()
        assert "decision" in schema_lower or "guiding" in schema_lower

    def test_json_schema_specifies_single_question(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        gq_idx = EXPERT_JSON_SCHEMA.find("guiding_question")
        snippet = EXPERT_JSON_SCHEMA[gq_idx:gq_idx+200]
        assert "single" in snippet.lower() or "one" in snippet.lower() or "question" in snippet.lower()


# ─────────────────────────────────────────────────────────────────────────────
# Integration: all P1 fields appear in PIReport and have correct defaults
# ─────────────────────────────────────────────────────────────────────────────

class TestPIReportP1Fields:

    _P1_FIELDS = [
        "evidence_base",
        "value_driver_ranking",
        "segment_fit_table",
        "feature_investment_posture",
        "pricing_model_analysis",
        "adversarial_review",
        "positioning_statement",
        "strategic_risks",
        "guiding_question",
    ]

    def test_all_p1_fields_on_pireport(self):
        from app.models.alignment import PIReport
        for field in self._P1_FIELDS:
            assert field in PIReport.model_fields, f"PIReport missing P1 field: {field}"

    def test_list_fields_default_to_empty_list(self):
        from app.models.alignment import PIReport
        import datetime
        r = PIReport(
            product_type="other",
            idea_submitted="test",
            executive_summary="test",
        )
        for field in ["value_driver_ranking", "segment_fit_table",
                      "feature_investment_posture", "adversarial_review", "strategic_risks"]:
            assert getattr(r, field) == [], f"{field} should default to []"

    def test_optional_fields_default_to_none(self):
        from app.models.alignment import PIReport
        r = PIReport(
            product_type="other",
            idea_submitted="test",
            executive_summary="test",
        )
        for field in ["evidence_base", "pricing_model_analysis",
                      "positioning_statement", "guiding_question"]:
            assert getattr(r, field) is None, f"{field} should default to None"

    def test_all_p1_sections_in_json_schema(self):
        from app.services.alignment_service import EXPERT_JSON_SCHEMA
        for field in self._P1_FIELDS:
            if field == "adversarial_review":
                continue   # S-06 is a second-pass call, not in the main schema
            assert field in EXPERT_JSON_SCHEMA, \
                f"EXPERT_JSON_SCHEMA missing P1 section: {field}"
